name: dmlcp
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - jupyter
  - matplotlib
  - opencv
  - pycairo
  - ollama
  - ollama-python
  - markdown
  - ruff
  - scikit-image
  - gdown
  - gradio
  - pip:
    - strip-markdown
    - py5canvas
    - mediapipe
